// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghI6N-9OuuNgU5taoqSx_v8T0oXCpqIQ',
    appId: '1:694467242945:web:7d56987ad5b2437251dd40',
    messagingSenderId: '694467242945',
    projectId: 'xstoreapp-cc684',
    authDomain: 'xstoreapp-cc684.firebaseapp.com',
    storageBucket: 'xstoreapp-cc684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU72DU1yKoV6BUqdTw2dZ6gGjNOhCkqoE',
    appId: '1:694467242945:android:48596ae41c29e0ab51dd40',
    messagingSenderId: '694467242945',
    projectId: 'xstoreapp-cc684',
    storageBucket: 'xstoreapp-cc684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhDgErOP5tlqVCpnsi5hKSOAsVd2FdDI',
    appId: '1:694467242945:ios:6b388b74b9d3f9eb51dd40',
    messagingSenderId: '694467242945',
    projectId: 'xstoreapp-cc684',
    storageBucket: 'xstoreapp-cc684.appspot.com',
    androidClientId: '694467242945-k6pbguhnf3gn6h7egana7hql17c9inp2.apps.googleusercontent.com',
    iosClientId: '694467242945-824t2l663apsflh9n1a58bhrq7a4h2g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.xstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuhDgErOP5tlqVCpnsi5hKSOAsVd2FdDI',
    appId: '1:694467242945:ios:6b388b74b9d3f9eb51dd40',
    messagingSenderId: '694467242945',
    projectId: 'xstoreapp-cc684',
    storageBucket: 'xstoreapp-cc684.appspot.com',
    androidClientId: '694467242945-k6pbguhnf3gn6h7egana7hql17c9inp2.apps.googleusercontent.com',
    iosClientId: '694467242945-824t2l663apsflh9n1a58bhrq7a4h2g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.xstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCghI6N-9OuuNgU5taoqSx_v8T0oXCpqIQ',
    appId: '1:694467242945:web:302724f9b62a2dc851dd40',
    messagingSenderId: '694467242945',
    projectId: 'xstoreapp-cc684',
    authDomain: 'xstoreapp-cc684.firebaseapp.com',
    storageBucket: 'xstoreapp-cc684.appspot.com',
  );

}